---
title: "cluster-destination-timeofday"
output:
  pdf_document
---

```{r 'setup', include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r 'imports', message = FALSE}
library(conflicted)
library(tidyverse) 
library(rlang)
library(gt)
  library(gtExtras)
conflicts_prefer(dplyr::filter)
```


```{r 'get-data'}
unzip(zipfile = "passenger_data.zip")
data = "passenger_data.csv" |>
	read_csv(
		col_types = cols(
			Wait_Time = col_integer(),
			C_Start = col_integer(),
			C0 = col_integer(),
			C_avg = col_double(),
			BFO_Dest_City = col_factor(),
			BFO_Destination_Country_Code = col_factor(),
			order = col_integer(),
			Pass_ID = col_integer(),
			Time_of_Day = col_integer(),
			Period_of_Week = col_factor(),
			Day_of_Week = col_factor(),
			Month = col_factor(),
			Season = col_factor(),
			Year = col_factor(),
			Flight_ID = col_integer(),
			Delay_in_Seconds = col_integer(),
			.default = col_guess()
		)
	) |>
  select(!Airfield) # all observations are from AUC
```

```{r 'data-edits'}
data = data |>
  mutate(
    BFO_Dest_City_or_CC = if_else( # split cities in Borealia, Vespuchia
      BFO_Destination_Country_Code %in% c("BOR", "VES"),
      true = BFO_Dest_City,
      false = BFO_Destination_Country_Code
    ) |>
      as_factor(),
    .after = BFO_Destination_Country_Code
  )
```

```{r 'data-display'}
cl = data |>
  summarise(
    n = n(),
    .by = c(
      Time_of_Day,
      BFO_Dest_City_or_CC
    )
  ) |>
  mutate(
    hour_start = case_when(
      Time_of_Day == 1 ~ "0:00",
      Time_of_Day == 2 ~ "6:00",
      Time_of_Day == 3 ~ "12:00",
      Time_of_Day == 4 ~ "18:00"
    ),
    hour_end = case_when(
      Time_of_Day == 1 ~ "6:00",
      Time_of_Day == 2 ~ "12:00",
      Time_of_Day == 3 ~ "18:00",
      Time_of_Day == 4 ~ "0:00"
    ),
    hours = 732,
    type = if_else(
      BFO_Dest_City_or_CC %in% c("QUE", "AUC", "SAF", "CWL"),
      true = "Domestic",
      false = "International"
    ) |>
      as_factor(),
    rate = n/732 # number of hours: 732 apiece
  ) |>
  filter(n > 20) |>
  relocate(BFO_Dest_City_or_CC, .after = hours) |>
  relocate(n, .before = rate) |>
  arrange(
    Time_of_Day,
    BFO_Dest_City_or_CC
  ) |>
  mutate( # change how Time_of_Day is displayed, **after** it's been ordered
    Time_of_Day = case_when(
      Time_of_Day == 1 ~ "Night",
      Time_of_Day == 2 ~ "Morning",
      Time_of_Day == 3 ~ "Afternoon",
      Time_of_Day == 4 ~ "Evening"
    )
  ) |>
  group_by(Time_of_Day)

gt(cl) |>
  tab_header(
    title = "Average passenger arrival rates at **AUC**" |>
      md(),
    subtitle = "by destination and time of day"
  ) |>
  cols_label(
    Time_of_Day = "Time",
    hour_start = "",
    hour_end = "",
    BFO_Dest_City_or_CC = "Destination",
    hours = "Hours",
    type = "Type",
    n = "Count",
    rate = "Arrivals/hour"
  ) |>
  tab_options(
    row_group.as_column = TRUE
  )
```
```{r}
dist = data |>
  summarise(
    avg_servers = mean(C0),
    .by = c(
      Time_of_Day,
      BFO_Dest_City_or_CC
    )
  ) |>
  filter(BFO_Dest_City_or_CC %in% cl$BFO_Dest_City_or_CC) |>
  filter(Time_of_Day != 1 | BFO_Dest_City_or_CC != "VES033") |>
  arrange(
    Time_of_Day,
    BFO_Dest_City_or_CC
  )
dist2 = data |>
  summarise(
    n = n(),
    .by = c(
      Time_of_Day,
      BFO_Dest_City_or_CC,
      C0
    )
  ) |>
  filter(BFO_Dest_City_or_CC %in% cl$BFO_Dest_City_or_CC) |>
  filter(Time_of_Day != 1 | BFO_Dest_City_or_CC != "VES033")
dist2 = dist2 |>
  mutate(
    total = sum(n),
    srv1 = if_else(
      C0 == 1,
      true = n/total*100,
      false = 0
    ),
    srv2 = if_else(
      C0 == 2,
      true = n/total*100,
      false = 0
    ),
    srv3 = if_else(
      C0 == 3,
      true = n/total*100,
      false = 0
    ),
    .by = c(
      Time_of_Day,
      BFO_Dest_City_or_CC
    )
  ) |>
  arrange(
    Time_of_Day,
    BFO_Dest_City_or_CC,
    C0
  ) |>
  summarise(
    across(srv1:srv3, sum),
    .by = c(
      Time_of_Day,
      BFO_Dest_City_or_CC
    )
  )
```
```{r}
joindist = dist |>
  left_join(
    dist2,
    by = join_by(
      Time_of_Day,
      BFO_Dest_City_or_CC
    )
  )
```
```{r}
cl2 = joindist |>
  mutate(
    hour_start = case_when(
      Time_of_Day == 1 ~ "0:00",
      Time_of_Day == 2 ~ "6:00",
      Time_of_Day == 3 ~ "12:00",
      Time_of_Day == 4 ~ "18:00"
    ),
    hour_end = case_when(
      Time_of_Day == 1 ~ "6:00",
      Time_of_Day == 2 ~ "12:00",
      Time_of_Day == 3 ~ "18:00",
      Time_of_Day == 4 ~ "0:00"
    ),
    .after = Time_of_Day
  ) |>
  mutate(
    type = if_else(
      BFO_Dest_City_or_CC %in% c("QUE", "AUC", "SAF", "CWL"),
      true = "Domestic",
      false = "International"
    ),
    .after = BFO_Dest_City_or_CC
  ) |>
  arrange(
    Time_of_Day,
    BFO_Dest_City_or_CC
  ) |>
  mutate( # change how Time_of_Day is displayed, **after** it's been ordered
    Time_of_Day = case_when(
      Time_of_Day == 1 ~ "Night",
      Time_of_Day == 2 ~ "Morning",
      Time_of_Day == 3 ~ "Afternoon",
      Time_of_Day == 4 ~ "Evening"
    )
  ) |>
  group_by(Time_of_Day)

gt(cl2) |>
  tab_header(
    title = "Average number of servers at **AUC**" |>
      md(),
    subtitle = "by destination and time of day"
  ) |>
  cols_label(
    Time_of_Day = "Time",
    hour_start = "",
    hour_end = "",
    BFO_Dest_City_or_CC = "Destination",
    type = "Type",
    avg_servers = "Avg. # Servers",
    srv1 = "1",
    srv2 = "2",
    srv3 = "3"
  ) |>
  tab_spanner(
    label = "Customers served with # of active servers",
    columns = c(srv1:srv3)
  ) |>
  tab_options(
    row_group.as_column = TRUE
  )
```
